apiVersion: batch/v1
kind: Job
metadata:
  name: api-seed
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: api-seed
          image: us.gcr.io/challenge-pl/api
          command: ['/bin/sh', '-c']
          #--skip-seed &&
          args:
            - npx prisma migrate deploy &&
              npx prisma generate &&
              npx prisma db seed
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: airbank-secrets
                  key: JWT_KEY
            - name: DB_HOST
              value: 'api-postgres'
            - name: 'DB_USER'
              valueFrom:
                secretKeyRef:
                  name: airbank-secrets
                  key: DB_USER
            - name: 'DB_PW'
              valueFrom:
                secretKeyRef:
                  name: airbank-secrets
                  key: DB_PW
            - name: 'DB_URL'
              value: postgresql://$(DB_USER):$(DB_PW)@$(DB_HOST):5432/airbankdb?schema=public
  backoffLimit: 3
