apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: us.gcr.io/challenge-pl/api
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: airbank-secret
                  key: JWT_KEY
            # TODO replace db for prisma
            - name: DB_HOST
              value: 'api-postgres'
            - name: 'DB_USER'
              valueFrom:
                secretKeyRef:
                  name: airbank-secret
                  key: DB_USER
            - name: 'DB_PW'
              valueFrom:
                secretKeyRef:
                  name: airbank-secret
                  key: DB_PW
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000